apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: postgres
spec:
  selector:
    matchLabels: {}
  componentKinds:
  - group: v1
    kind: Service
  - group: networking.k8s.io
    kind: Ingress
  - group: cert-manager.io
    kind: Certificate
  - group: apps
    kind: StatefulSet
  - group: apps
    kind: Deployment
  - group: batch
    kind: CronJob
  - group: batch
    kind: Job
  descriptor:
    type: postgres
    version: 0.2.8
    description: postgres as a service for kubernetes
    icons:
    - src: https://plural-assets.s3.us-east-2.amazonaws.com/uploads/repos/964f6549-30f1-46c3-ad03-a31166120a5c/postgres.png?v=63819019749
    

    {{- if .Values.global }}
    {{- if .Values.global.application }}
    {{- if .Values.global.application.links }}
    links:
    {{ toYaml .Values.global.application.links | nindent 6 }}
    {{- end }}
  {{- if .Values.global.application.info }}
  info:
  {{ toYaml .Values.global.application.info | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- end }}
