apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: sentry
spec:
  selector:
    matchLabels: {}
  componentKinds:
  - group: v1
    kind: Service
  - group: networking.k8s.io
    kind: Ingress
  - group: cert-manager.io
    kind: Certificate
  - group: apps
    kind: StatefulSet
  - group: apps
    kind: Deployment
  - group: batch
    kind: CronJob
  - group: batch
    kind: Job
  descriptor:
    type: sentry
    version: 0.2.15
    description: error monitoring for multiple languages and platforms
    icons:
    - src: https://plural-assets.s3.us-east-2.amazonaws.com/uploads/repos/01089244-ac87-41e4-b464-2cbef89756cd/sentry.png?v=63819019769
    

    {{- if .Values.global }}
    {{- if .Values.global.application }}
    {{- if .Values.global.application.links }}
    links:
    {{ toYaml .Values.global.application.links | nindent 6 }}
    {{- end }}
  {{- if .Values.global.application.info }}
  info:
  {{ toYaml .Values.global.application.info | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- end }}
