apiVersion: plural.sh/v1alpha1
kind: Dependencies
metadata:
  description: nextcloud azure setup
  version: 0.1.3
spec:
  dependencies:
  - name: azure-bootstrap
    repo: bootstrap
    type: terraform
    version: '>= 0.1.1'
  providers:
  - azure
