apiVersion: v2
name: nextcloud
description: A helm chart for nextcloud
version: 0.1.0
appVersion: 0.1.27
dependencies:
- name: nextcloud
  version: 0.1.27
  repository: cm://app.plural.sh/cm/nextcloud
  condition: nextcloud.enabled
