apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: minio
spec:
  selector:
    matchLabels: {}
  componentKinds:
  - group: v1
    kind: Service
  - group: networking.k8s.io
    kind: Ingress
  - group: cert-manager.io
    kind: Certificate
  - group: apps
    kind: StatefulSet
  - group: apps
    kind: Deployment
  - group: batch
    kind: CronJob
  - group: batch
    kind: Job
  descriptor:
    type: minio
    version: 0.1.53
    description: High Performance, Kubernetes Native Object Storage
    icons:
    - src: https://plural-assets.s3.us-east-2.amazonaws.com/uploads/repos/20067709-663b-4100-9f18-e213cdf4f165/minio.png?v=63819019706
    

    {{- if .Values.global }}
    {{- if .Values.global.application }}
    {{- if .Values.global.application.links }}
    links:
    {{ toYaml .Values.global.application.links | nindent 6 }}
    {{- end }}
  {{- if .Values.global.application.info }}
  info:
  {{ toYaml .Values.global.application.info | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- end }}
